Emit events during remediation process
medik8s/machine-deletion-remediation pull request #96
Opened 2023-10-02 13:55 UTC by clobrano

fixes: https://issues.redhat.com/browse/ECOPROJECT-1664

Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

2023-10-02 13:57 UTC, clobrano commented
/test ?

2023-10-02 13:58 UTC, clobrano commented
/test 4.14-openshift-e2e

2023-10-06 07:34 UTC, clobrano commented
/test 4.14-openshift-e2e

2023-10-09 14:37 UTC, slintes requested changes
I think we are missing events in the `if machine == nil {}` block, otherwise 👍🏼

2023-12-20 10:07 UTC, clobrano commented
Converting the PR to WIP to prevent tests execution

2024-01-02 13:16 UTC, clobrano commented
/retest

2024-01-02 15:06 UTC, clobrano commented
/test 4.14-openshift-e2e

2024-01-02 17:26 UTC, clobrano commented
/retest

2024-01-03 14:48 UTC, razo7 requested changes
Every time we are about to delete a machine we emit an event `MachineDeletionRequested` I would expect to find (and to find it) this event in MDR unit tests, as another assertion that we have (or have not) reached machine deletion.
Except that there are small nits.

2024-01-03 14:48 UTC, razo7 commented on controllers/machinedeletionremediation_controller.go
> +			if err == nil {
NIT: I am not sure it is needed. 
Function `updateConditions` returns an error only when it was called with unknown conditionChangeReason when `remediationFinishedMachineDeleted` reason is already found/defined in the function.

2024-01-03 14:48 UTC, razo7 commented on controllers/machinedeletionremediation_controller_test.go
> +					verifyEvent("Warning", "RemediationSkippedNodeNotFound", "failed to fetch node")
Instead of `"Warning"` we can use `corev1.EventTypeWarning`, and `corev1.EventTypeNormal` instead of "Normal"

2024-01-04 15:20 UTC, clobrano commented on controllers/machinedeletionremediation_controller_test.go
> +		case <-time.After(1 * time.Second):
this should work as timeout. If we don't get any other event in 1 second exit

2024-01-04 15:27 UTC, razo7 commented
/lgtm 
I didn't see a check if some events are not emitted in the unit tests (`verifyNoEvent`) which is also a nice indication of a healthy flow of each test. But this is not critical and probably not even relevant here.
Giving others a chance to review as well, feel free to unhold
/hold

2024-01-04 15:28 UTC, clobrano commented
moved to draft to avoid wasting tests

2024-01-04 16:30 UTC, clobrano commented
/test 4.14-openshift-e2e

2024-01-08 15:34 UTC, razo7 commented
/lgtm

2024-01-08 16:40 UTC, slintes requested changes
one comment inside, otherwise lgtm

2024-01-08 16:40 UTC, slintes commented on controllers/machinedeletionremediation_controller.go
> +	commonevents.NormalEvent(r.Recorder, mdr, machineDeletionRequestedEventReason, machineDeletionRequestedEventMessage)
this this event says "requested" (past tense) it should emitted after successful machine deletion

2024-01-09 09:59 UTC, slintes approved these changes

2024-01-09 10:00 UTC, slintes commented
/hold cancel

2024-01-09 10:02 UTC, merged